# jdbc:postgresql://<host>:<port>/<database_name>
spring.datasource.url=${POSTGRES_URL:}
# nom + mdp de la db
spring.datasource.username=${POSTGRES_USERNAME:}
spring.datasource.password=${POSTGRES_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
