spring.application.name=GenieLogicielMeteoConsommation

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/meteoconsommation
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Optionnel mais conseillé
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true